"use strict";
export const languages = [
    ["ar", "Arabic", "العربية"],
    ["bg", "Bulgarian", "български език"],
    ["br", "Breton", "brezhoneg"],
    ["ca", "Catalan", "català"],
    ["cs", "Czech", "čeština"],
    ["da", "Danish", "dansk"],
    ["de", "German", "Deutsch"],
    ["el", "Greek", "ελληνικά"],
    ["en", "English", "English"],
    // ["en_GB", "English (Great Britain)", "English (Great Britain)"],
    ["eo", "Esperanto", "Esperanto"],
    ["es", "Spanish", "Español"],
    ["fi", "Finnish", "suomi"],
    ["fr", "French", "français"],
    ["he", "Hebrew", "עברית"],
    ["hr", "Croatian", "hrvatski jezik"],
    ["hu", "Hungarian", "magyar"],
    ["is", "Icelandic", "Íslenska"],
    ["it", "Italian", "Italiano"],
    ["ja", "Japanese", "日本語"],
    ["lt", "Lithuanian", "lietuvių kalba"],
    ["mk", "Macedonian", "македонски јазик"],
    ["nb", "Norwegian", "Norsk Bokmål"],
    ["nl", "Dutch", "Nederlands"],
    ["nn", "Norwegian", "Norsk"],
    ["pl", "Polish", "polszczyzna"],
    // ["pt_BR", "Portuguese (Brazil)", "Português"],
    // ["pt_PT", "Portuguese (Portugal)", "Português"],
    ["pt_PT", "Portuguese", "Português"],
    ["ro", "Romanian", "Română"],
    ["ru", "Russian", "русский"],
    ["sk", "Slovak", "Slovenčina"],
    ["sl", "Slovenian", "Slovenščina"],
    ["sq", "Albanian", "Shqip"],
    ["sr", "Serbian", "српски језик"],
    ["sv", "Swedish", "Svenska"],
    ["tr", "Turkish", "Türkçe"],
    ["uk", "Ukrainian", "Українська"],
    ["vi", "Vietnamese", "Tiếng Việt"],
    // ["zh_CN", "Chinese (China)", "中文"],
    // ["zh_HK", "Chinese (Hong Kong)", "中文"],
    // ["zh_TW", "Chinese (Taiwan)", "中文"],
    ["zh_TW", "Chinese", "中文"]
]
