"use strict";
export const wiki_links = [
    {"i":"postgresql", "w":"PostgreSQL"},
    {"i":"Export GEDCOM Extensions", "w":"GEDCOM_Extensions"},
    {"i":"JSON Export", "w":""},
    {"i":"Prolog Export", "w":""},
    {"i":"Raw Export", "w":"ExportRaw"},
    {"i":"ex_sqlite", "w":"SQLite_Export_Import"},
    {"i":"Birthdays", "w":"BirthdaysGramplet"},
    {"i":"Clock Gramplet", "w":"Gramplets#Cairo_Clock_Example"},
    {"i":"Collections Clipboard Gramplet", "w":"Collections_Clipboard_Gramplet"},
    {"i":"DNASegmentMap", "w":"Addon:DNASegmentMapGramplet"},
    {"i":"Data Entry Gramplet", "w":"DataEntryGramplet"},
    {"i":"DateCalculator", "w":"DateCalculator"},
    {"i":"Deep Connections Gramplet", "w":"Deep_Connections_Gramplet"},
    {"i":"Descendant Count Gramplet", "w":"Descendant_Count_Gramplet"},
    {"i":"Edit Image Exif Metadata", "w":"Gramps_5.1_Wiki_Manual_-_Gramplets#Image_Metadata"},
    {"i":"Extended Family Attributes", "w":""},
    {"i":"Extended Person Attributes", "w":""},
    {"i":"Family Overview", "w":""},
    {"i":"Form Gramplet", "w":"Form_Addons"},
    {"i":"GetGOV Gramplet", "w":"Addon:GetGOV"},
    {"i":"Headline News", "w":"HeadlineNewsGramplet"},
    {"i":"House Timeline", "w":"House_Timeline_Gramplet"},
    {"i":"Import Gramplet", "w":"ImportGramplet"},
    {"i":"LastChangeGramplet", "w":"LastChange"},
    {"i":"MediaBrowser", "w":"Addon:MediaBrowserGramplet"},
    {"i":"Note Gramplet", "w":"NoteGramplet"},
    {"i":"Participants", "w":"Addon:ParticipantsGramplet"},
    {"i":"Person Overview", "w":""},
    {"i":"Photo Tagging", "w":"Photo_Tagging_Gramplet"},
    {"i":"Place Coordinates", "w":"PlaceCoordinateGramplet"},
    {"i":"PlaceCleanup", "w":"Addon:PlaceCleanupGramplet"},
    {"i":"PlaceUpdate", "w":"PlaceUpdate_Gramplet"},
    {"i":"Prerequisites Checker Gramplet", "w":"Addon:Prerequisites_Checker_Gramplet"},
    {"i":"Python Gramplet", "w":"Python_Shell_Gramplet"},
    {"i":"Related Relatives Gramplet", "w":"RelatedRelativesGramplet"},
    {"i":"This Day in Family History", "w":"This_Day_In_Family_History"},
    {"i":"HtreePedigreeView", "w":"Addon:HtreePedigreeView"},
    {"i":"QuiltView", "w":"Quilt_Chart"},
    {"i":"TimelinePedigreeView", "w":"TimelinePedigreeView"},
    {"i":"combinedview", "w":"Addon:CombinedView"},
    {"i":"geoIDplaceCoordinateGramplet", "w":""},
    {"i":"geoancestor", "w":"Addon:AncestorsMap"},
    {"i":"graphview", "w":"Graph_View"},
    {"i":"lifelinechartancestorview", "w":"Life_Line_Chart_View"},
    {"i":"lifelinechartdescendantview", "w":"Life_Line_Chart_View"},
    {"i":"JSON Import", "w":""},
    {"i":"im_sqlite", "w":"SQLite_Export_Import"},
    {"i":"GoogleEarth", "w":"Map_Services"},
    {"i":"DE Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"FR Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"NL Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"PluginManager", "w":"Plugin_Manager_Plugin"},
    {"i":"RU Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"RestoreHist", "w":""},
    {"i":"ThemesPrefs", "w":"Addon:Themes"},
    {"i":"UK Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"US Web Connect Pack", "w":"Web_Connect_Pack"},
    {"i":"libaccess", "w":"Libaccess"},
    {"i":"libwebconnect", "w":""},
    {"i":"NumberOfAncestorsQuickview", "w":"Addon:NumberOfAncestorsQuickView"},
    {"i":"NumberOfDescendantsQuickview", "w":"Number_Of_Descendants_Quickview"},
    {"i":"allnames", "w":"All_Names_Quickview"},
    {"i":"biographyquickview", "w":""},
    {"i":"timelinequickview", "w":"Timeline_Quickview"},
    {"i":"AncestorFill", "w":""},
    {"i":"DescendantBook", "w":""},
    {"i":"Descendants Lines", "w":"DescendantsLines"},
    {"i":"DetailedDescendantBook", "w":""},
    {"i":"DynamicWeb", "w":"DynamicWeb_report"},
    {"i":"FamilySheet", "w":"Family_Sheet"},
    {"i":"FamilyTree", "w":"Family_Tree"},
    {"i":"Heatmap", "w":"Addon:HeatmapWebReport"},
    {"i":"LastChangeReport", "w":""},
    {"i":"LinesOfDescendency", "w":"Lines_of_Descendency_Report"},
    {"i":"ListeEclair", "w":""},
    {"i":"MediaReport", "w":"Addon:MediaReport"},
    {"i":"PedigreeChart", "w":"PedigreeChart"},
    {"i":"PersonEverythingReport", "w":"PersonEverything_Report"},
    {"i":"Repositories Report", "w":"RepositoriesReport"},
    {"i":"Repositories Report Options", "w":"RepositoriesReport"},
    {"i":"SourcesCitationsReport", "w":"Addon:SourcesCitationsReport"},
    {"i":"TimePedigreeHTML", "w":""},
    {"i":"TodoReport", "w":"ToDoReport"},
    {"i":"d3-ancestralcollapsibletree", "w":"D3_Ancestral/Descendant_Charts"},
    {"i":"d3-ancestralfanchart", "w":"D3_Ancestral/Descendant_Charts"},
    {"i":"d3-descendantindentedtree", "w":"D3_Ancestral/Descendant_Charts"},
    {"i":"database-differences-report", "w":"Database_Differences_Report"},
    {"i":"denominoviso", "w":"DenominoViso"},
    {"i":"det_descendant_report_i", "w":"Descendant and Detailed Descendant Book Reports"},
    {"i":"double_cousins", "w":"Addon:DoubleCousinReport"},
    {"i":"gt_ancestor", "w":"Addon:GenealogyTree"},
    {"i":"gt_descendant", "w":"Addon:GenealogyTree"},
    {"i":"gt_grandparent", "w":"Addon:GenealogyTree"},
    {"i":"gt_sandclock", "w":"Addon:GenealogyTree"},
    {"i":"gt_sandclock_family", "w":"Addon:GenealogyTree"},
    {"i":"networkchart", "w":"NetworkChart"},
    {"i":"ActivePerson", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"HasFamilyEventRole", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"HasPersonEventRole", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"HasSourceParameter", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"IsRelatedWithFilterMatch", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"MatrilinealProgenitrix", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"PatrilinealProgenitor", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"PersonsInFamilyFilterMatch", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"ageatdeath", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"associationsofpersonmatch", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"degreesofseparation", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"familieswitheventfiltermatch", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"isfamilyfiltermatchevent", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"mtinheritance", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"mtinheritanceoffiltermatch", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"multipleparents", "w":"Rule_expansions#FilterRules_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"xchromancestors", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"xchromdescendants", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"yinheritance", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"yinheritanceoffiltermatch", "w":"Rule_expansions#FilterRules2_:_Plugin_Manager_Rulebook_Collection"},
    {"i":"AttachSource", "w":"AttachSourceTool"},
    {"i":"AvatarGenerator", "w":"Addon:AvatarGenerator"},
    {"i":"EventDescriptionEditor", "w":"Addon:EventDescriptionEditor"},
    {"i":"FamilyRelationshipTool", "w":"Addon:FamilyRelationship"},
    {"i":"FixCoords", "w":""},
    {"i":"PlaceCompletion", "w":"Place_completion_tool"},
    {"i":"RemoveTagTool", "w":"Addon:AddRemoveTagTool"},
    {"i":"SetAttribute", "w":"SetAttributeTool"},
    {"i":"SetPrivacyTool", "w":"Addon:SetPrivacyTool"},
    {"i":"Topola", "w":"Interactive_Family_Tree"},
    {"i":"associationstool", "w":""},
    {"i":"birthorder", "w":"BirthOrderTool"},
    {"i":"calculateestimateddates", "w":"Calculate_Estimated_Dates"},
    {"i":"chgivenname", "w":"Fix_Capitalization_of_Given_Names"},
    {"i":"climerge", "w":""},
    {"i":"downloadmedia", "w":"Addon:DownloadMedia"},
    {"i":"excity", "w":"Extract_Place_Data_from_a_Place_Title"},
    {"i":"import_merge", "w":"Import_Merge_Tool"},
    {"i":"mediamerge", "w":"Addon:MediaMerge"},
    {"i":"mediaverify", "w":"Media_Verify_Tool"},
    {"i":"notecleanup", "w":"NoteCleanupTool"},
    {"i":"syncAssociations", "w":"Addon:SyncAssociation"},
    {"i":"thumbgen", "w":"Addon:ThumbnailGenerator"},
    {"i":"typecleanup", "w":"Types_Cleanup_Tool"},
]